---
# Entry point for all Zookeeper cluster tasks.
#
# Use tags to control which group of tasks to run.
# Usage examples:
#   ansible-playbook ... --tags node_setup
#   ansible-playbook ... --tags cluster_update
#   ansible-playbook ... --tags "node_setup,cluster_update"

- name: Setup individual Zookeeper node (data & log directories, myid, run as a service)
  include_tasks: node_setup.yml
  tags:
    - node_setup

- name: Update cluster-wide zookeepers config and orchestrate rolling restart
  include_tasks: cluster_update.yml
  tags:
    - cluster_update

- name: Rolling restart, stop one node, start it, move to next
  include_tasks: rolling_restart.yml
  tags:
    - cluster_update
