---
#########################################################
###                ZOOKEEPER CONFIGS                  ###
#########################################################
- name: Ensure ZooKeeper config directory exists
  file:
    path: "{{ kafka_dir }}/config"
    state: directory
    mode: '0755'

- name: Ensure ZooKeeper data directory exists
  file:
    path: "{{ zk_data_dir }}"
    state: directory
    mode: '0755'

- name: Set ZooKeeper ID (myid) by matching IP to zookeeper group
  set_fact:
    zk_id: >-
      {{
        (groups['zookeepers']
          | map('extract', hostvars, ['ansible_host'])
          | list)
          .index(ansible_host) + 1
      }}
  when: ansible_host in (groups['zookeepers'] | map('extract', hostvars, ['ansible_host']) | list)

- name: Write ZooKeeper myid
  copy:
    content: "{{ zk_id }}"
    dest: "{{ zk_data_dir }}/myid"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0644'

- name: Deploy initial zookeeper.properties for new node
  template:
    src: "{{ playbook_dir }}/../templates/zookeeper.properties.j2"
    dest: "{{ kafka_dir }}/config/zookeeper.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0644'
    backup: yes


#########################################################
###              ZOOKEEPER AS A SERVICE               ###
#########################################################
- name: Create Zookeeper data and log directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0755'
    recurse: yes
  loop:
    - "{{ zk_data_dir }}"
    - "{{ zk_log_dir }}"

- name: Create systemd service for Zookeeper
  copy:
    dest: /etc/systemd/system/zookeeper.service
    content: |
      [Unit]
      Description=Apache Zookeeper server
      After=network.target

      [Service]
      Type=simple
      User={{ kafka_user }}
      ExecStart={{ kafka_dir }}/bin/zookeeper-server-start.sh {{ kafka_dir }}/config/zookeeper.properties
      ExecStop={{ kafka_dir }}/bin/zookeeper-server-stop.sh
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
  notify: Reload systemd

- name: Enable ZooKeeper service (but don't start yet)
  systemd:
    name: zookeeper
    enabled: yes
    daemon_reload: yes
