- name: Ensure required OS packages are installed
  apt:
    name:
      - wget
      - ca-certificates
      - zip
      - net-tools
      - vim
      - nano
      - tar
      - netcat
      - openjdk-21-jdk
    state: present
  when: ansible_os_family == "Debian"

- name: Disable swap (set vm.swappiness=1)
  sysctl:
    name: vm.swappiness
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: Persist swappiness setting in /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: 'vm.swappiness=1'
    state: present
