- name: Generate host/ip pairs from inventory to /etc/hosts
  set_fact:
    all_hosts_block: |
      {% for host in groups['all'] %}
      {{ hostvars[host].ansible_host }} {{ host }}
      {% endfor %}

- name: Inject Kafka host entries into /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: "{{ all_hosts_block }}"
    marker: "# {mark} ANSIBLE MANAGED KAFKA HOSTS"
