---
- name: Wait for Zookeeper to be up
  wait_for:
    port: {{ zk_port }}
    state: started
    delay: 2
    timeout: 30

- name: Health check - Zookeeper "ruok" 4lw
  shell: echo "ruok" | nc localhost 2181
  register: ruok_out
  failed_when: "'imok' not in ruok_out.stdout"
  changed_when: false
