- name: Deploy Kafka host entries to /etc/hosts
  hosts: brokers
  become: true

  tasks:
    - name: Generate Kafka hosts block from all_hosts
      set_fact:
        kafka_hosts_block: |
          {% for host in all_hosts %}
          {{ host.ip }} {{ host.hostname }}
          {% endfor %}

    - name: Inject Kafka host entries into /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: "{{ kafka_hosts_block }}"
        marker: "# {mark} ANSIBLE MANAGED KAFKA HOSTS"
