- name: Deploy Kafka host entries to /etc/hosts
  hosts: brokers
  become: true
  gather_facts: false

  tasks:
    # create a list of host/ip pairs using inventory data
    - name: Generate host/ip pairs from inventory
      set_fact:
        all_hosts_block: >-
          {{
            groups['all']
            | map('extract', hostvars, ['ansible_host'])
            | zip(groups['all'])
            | map('reverse')
            | map('join', ' ')
            | join('\n')
          }}

    - name: Inject Kafka host entries into /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: "{{ all_hosts_block }}"
        marker: "# {mark} ANSIBLE MANAGED KAFKA HOSTS"
