- name: Configure Kafka hosts resolution
  hosts: kafka_brokers
  become: true
  
  tasks:
    - name: Add Kafka host entries to /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          # Kafka cluster nodes
          172.31.9.1 kafka1
          172.31.9.1 zookeeper1
          172.31.19.230 kafka2
          172.31.19.230 zookeeper2
          172.31.35.20 kafka3
          172.31.35.20 zookeeper3
          172.31.88.119 webtools
        marker: "# {mark} ANSIBLE MANAGED KAFKA HOSTS"
