---
# 1. Prepare new broker node (provision dirs, service, etc.)
- name: Setup new broker node
  hosts: broker_newnode
  become: true
  roles:
    - role: brk01_newnode


# 2. Update configs on ALL broker cluster nodes
- name: Update cluster-wide brokers config
  hosts: brokers
  become: true
  roles:
    - role: brk02_ensemble
  