---
# 1. Prepare new ZooKeeper node (provision dirs, myid, service, etc.)
- name: Setup new ZooKeeper node
  hosts: zookeeper_newnode
  become: true
  roles:
    - role: zk01_newnode


# 2. Update configs on ALL ZooKeeper cluster nodes
- name: Update cluster-wide zookeepers config
  hosts: zookeepers
  become: true
  roles:
    - role: zk02_ensemble
