- name: Download and Install Kafka 3.7.2 on Brokers
  hosts: kafka_brokers
  become: yes

  vars_files:
    - "../group_vars/binaries_config.yml"
  
  vars:
    download_dest: "/tmp/{{ kafka_archive }}"
    extract_dest: "/opt/"
  
  tasks:
    - name: Download Kafka {{ kafka_version }} from Apache
      get_url:
        url: "{{ kafka_url }}"
        dest: "{{ download_dest }}"
        mode: '0644'
        force: no

    - name: Extract Kafka binaries to {{ extract_dest }}
      unarchive:
        src: "{{ download_dest }}"
        dest: "{{ extract_dest }}"
        remote_src: yes
        creates: "{{ extract_dest }}/kafka_{{ scala_version }}-{{ kafka_version }}"

    - name: Rename extracted Kafka folder to kafka_{{ kafka_version }}
      command: mv {{ extract_dest }}/kafka_{{ scala_version }}-{{ kafka_version }} {{ kafka_dir }}
      args:
        creates: "{{ kafka_dir }}"

    - name: Remove Kafka archive after extraction
      file:
        path: "{{ download_dest }}"
        state: absent
