- name: Download and Install Kafka 3.7.2 on Brokers
  hosts: kafka_brokers
  become: yes
  vars:
    kafka_version: "3.7.2"
    scala_version: "2.13"
    kafka_archive: "kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    kafka_url: "https://downloads.apache.org/kafka/{{ kafka_version }}/{{ kafka_archive }}"
    download_dest: "/tmp/{{ kafka_archive }}"
    extract_dest: "/opt/"
    final_kafka_dir: "/opt/kafka_{{ kafka_version }}"
  
  tasks:
    - name: Download Kafka {{ kafka_version }} from Apache
      get_url:
        url: "{{ kafka_url }}"
        dest: "{{ download_dest }}"
        mode: '0644'
        force: no

    - name: Extract Kafka binaries to {{ extract_dest }}
      unarchive:
        src: "{{ download_dest }}"
        dest: "{{ extract_dest }}"
        remote_src: yes
        creates: "{{ extract_dest }}/kafka_{{ scala_version }}-{{ kafka_version }}"

    - name: Rename extracted Kafka folder to kafka_{{ kafka_version }}
      command: mv {{ extract_dest }}/kafka_{{ scala_version }}-{{ kafka_version }} {{ final_kafka_dir }}
      args:
        creates: "{{ final_kafka_dir }}"

    - name: Remove Kafka archive after extraction
      file:
        path: "{{ download_dest }}"
        state: absent
