- name: Deploy ZooKeeper Configuration
  hosts: zookeepers
  become: yes

  tasks:
    - name: Ensure ZooKeeper config directory exists
      file:
        path: "{{ kafka_config_dir }}"
        state: directory
        mode: '0755'

    - name: Set ZooKeeper ID (myid) based on inventory
      set_fact:
        zk_id: "{{ groups['zookeepers'].index(inventory_hostname) + 1 }}"

    # - name: Write ZooKeeper myid
    #   copy:
    #     content: "{{ zk_id }}"
    #     dest: /var/lib/zookeeper/myid
    #     owner: "{{ kafka_user }}"
    #     group: "{{ kafka_group }}"
    #     mode: '0644'

    - name: Deploy ZooKeeper
      template:
        src: ../templates/zookeeper.properties.j2
        dest: "{{ kafka_config_dir }}/zookeeper.properties"
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"
        mode: '0644'
        backup: yes

    - name: Start ZooKeeper service
      service:
        name: zookeeper
        state: started
