- name: Deploy Zookeeper Configurations
  hosts: zookeeper
  become: true

  vars_files:
    - "../group_vars/binaries_config.yml"

  vars:
    data_dir: "/data/zookeeper"
    client_port: 2181
    max_client_cnxns: 0
    tick_time: 2000
    init_limit: 10
    sync_limit: 5
    whitelist_commands: "ruok,stat,conf,mntr,cons,dump,srvr,envi,wchs"

    zookeepers:
      "1": "zookeeper1"
      "2": "zookeeper2"
      "3": "zookeeper3"

  tasks:
    - name: Stop ZooKeeper service
      service:
        name: zookeeper
        state: stopped
        
    - name: Deploy ZooKeeper config
      template:
        src: ../templates/zookeeper.properties.j2
        dest: "{{ kafka_config_dir }}/zookeeper.properties"
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"
        mode: "0644"
        backup: yes
        
    - name: Start ZooKeeper service
      service:
        name: zookeeper
        state: started
